MarketHub/Controllers/ManageUsersController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using StoreApp.Models;
using StoreApp.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StoreApp.Controllers
{
    public class ManageUsersController:Controller
    {
        StoreAppContext cntx;
        public ManageUsersController(StoreAppContext tcntx)
        {
            this.cntx = tcntx;
        }

        [HttpGet]
        public IActionResult SignUp()
        {
            return View();
        }

        [HttpPost]
        public IActionResult SignUp(UserVM rec)
        {
            if (ModelState.IsValid)
            {
                User urec = new User();
                urec.Address = rec.Address;
                urec.EmailID = rec.EmailID;
                urec.MobileNo = rec.MobileNo;
                urec.FirstName = rec.FirstName;
                urec.LastName = rec.LastName;
                urec.Password = rec.Password;
                this.cntx.Users.Add(urec);
                this.cntx.SaveChanges();
                return RedirectToAction("SignIn");
            }
            return View(rec);
        }

        [HttpGet]
        public IActionResult SignIn()
        {
            return View();
        }


        [HttpPost]
        public IActionResult SignIn(LoginVM rec)
        {
            if (ModelState.IsValid)
            {
                var strec = this.cntx.Users.SingleOrDefault(p => p.EmailID == rec.EmailID && p.Password == rec.Password);
                if (strec != null)
                {
                    HttpContext.Session.SetString("UserID", strec.UserID.ToString());
                    HttpContext.Session.SetString("UserName", strec.FirstName);
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ModelState.AddModelError("", "Invalid Email ID or Password!");
                    return View(rec);
                }
            }
            return View(rec);
        }

        [HttpGet]   
        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("SignIn");
        }
    }
}

MarketHub/Views/ManageUsers/SignIn.cshtml
@model LoginVM
    <div class="men">
        <div class="container">
            <div class="register">
                <div class="col-md-6 login-left">
                    <h3>NEW CUSTOMERS</h3>
                    <p>By creating an account with our store, you will be able to move through the checkout process faster, store multiple shipping addresses, view and track your orders in your account and more.</p>
                    <a class="acount-btn" asp-action="SignUp" asp-controller="ManageUsers">Create an Account</a>
                </div>
                <div class="col-md-6 login-right">
                    <h3>REGISTERED CUSTOMERS</h3>
                    <p>If you have an account with us, please log in.</p>
                    <form asp-action="SignIn" asp-controller="ManageUsers" method="post"> 
                        <div asp-validation-summary="ModelOnly" class="alert-danger">

                        </div>
                        <div>
                            <span>Email Address<label>*</label></span>
                            <input asp-for="EmailID">
                            <span asp-validation-for="EmailID"></span>
                        </div>
                        <div>
                            <span>Password<label>*</label></span>
                            <input asp-for="Password">
                            <span asp-validation-for="Password"></span>
                        </div>
                     
                        <input type="submit" value="Login">
                    </form>
                </div>
                <div class="clearfix"> </div>
            </div>
        </div>
    </div>

MarketHub/Views/ManageUsers/SignUp.cshtml
@model UserVM

    <div class="men">
        <div class="container">
            <div class="col-md-12 register">
                <form asp-action="SignUp" asp-controller="ManageUsers" method="post">
                    <div class="register-top-grid">
                        <h3>PERSONAL INFORMATION</h3>
                        <div>
                            <span>First Name<label>*</label></span>
                            <input asp-for="FirstName" />
                            <span asp-validation-for="FirstName"></span>
                        </div>
                        <div>
                            <span>Last Name<label>*</label></span>
                            <input asp-for="LastName" />
                            <span asp-validation-for="LastName"></span>
                        </div>
                        <div>
                            <span>Email Address<label>*</label></span>
                            <input asp-for="EmailID" />
                            <span asp-validation-for="EmailID"></span>
                        </div>
                        <div>
                            <span>Address<label>*</label></span>
                            <input asp-for="Address" />
                            <span asp-validation-for="Address"></span>
                        </div>
                        <div>
                            <span>Mobile No<label>*</label></span>
                            <input asp-for="MobileNo" />
                            <span asp-validation-for="MobileNo"></span>
                        </div>
                        <div>
                             &nbsp;
                        </div>
                        <div class="clearfix"> </div>
                    </div>
                    <div class="register-bottom-grid">
                        <h3>LOGIN INFORMATION</h3>
                        <div>
                            <span>Password<label>*</label></span>
                            <input asp-for="Password" />
                        </div>
                        <div>
                            <span>Confirm Password<label>*</label></span>
                            <input asp-for="ConfirmPassword" />
                            <span asp-validation-for="ConfirmPassword"></span>
                        </div>
                        <div class="clearfix"> </div>
                    </div>
                    <div class="clearfix"> </div>
                    <div>
                        <input type="submit" value="submit">
                        <div class="clearfix"> </div>
                    </div>
                </form>
            </div>
        </div>
    </div>